### Assignment 1

**TASK**: print('My name is ' + name + '. I am now ' + age + ' years old,\ and in 6 years I\'ll be ' + ' years old.')

In [49]:
name = "Pau"
age = 22

print('My name is ' + name + '. I am now ' + str(age) + ' years old,\
 and in 6 years I\'ll be ' + str(age + 6) + ' years old.')

My name is Pau. I am now 22 years old, and in 6 years I'll be 28 years old.


### Assignment 2

###### 1. Create a list of 15 numbers from 4 to 100.

In [19]:
import numpy as np

In [36]:
np.linspace(4,100,15)

array([  4.        ,  10.85714286,  17.71428571,  24.57142857,
        31.42857143,  38.28571429,  45.14285714,  52.        ,
        58.85714286,  65.71428571,  72.57142857,  79.42857143,
        86.28571429,  93.14285714, 100.        ])

###### 2. Round those numbers to the nearest integer, and store in another variable.

In [40]:
np.round_(np.linspace(4,100,15))

round = np.round_(np.linspace(4,100,15))

###### 3. Print out #2.

In [47]:
round

array([  4.,  11.,  18.,  25.,  31.,  38.,  45.,  52.,  59.,  66.,  73.,
        79.,  86.,  93., 100.])

###### 4. Print out the square root of each number in the list.

In [48]:
np.sqrt(np.linspace(4,100,15))

array([ 2.        ,  3.29501788,  4.20883425,  4.95695759,  5.60611911,
        6.18754509,  6.71884344,  7.21110255,  7.6718409 ,  8.10643483,
        8.51888658,  8.91227083,  9.2890104 ,  9.65105472, 10.        ])